
class Fields:
    KEY_IDENTIFIER = 'Identifier'
    TAX_RATE = 'TAX_RATE'
    NET_AMOUNT = 'NET_AMOUNT'
    TOTAL_AMOUNT = 'TOTAL_AMOUNT'
    TAX_AMOUNT = 'TAX_AMOUNT'
    VAT_NO = 'VAT_NO'
    IBAN_EXTRACTED = 'IBAN_EXTRACTED'
    PAYMENT_TERMS = 'PAYMENT_TERMS'
    INVOICE_DATE = 'INVOICE_DATE'
    DELIVERY_DATE = 'DELIVERY_DATE'


PAYMENT_TERMS_STOP_WORDS = ['zum', 'ohne Abzug', 'Zahlbar', 'netto']