name: Read the docs
on: 
  push:
    branches: [ master ]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: fellowconsulting/ephesoft-automation
      tags: latest
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/build/html/
    
    